// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCjfmNqQ6znpD_sOg9nKWkJp6KFekli-0',
    appId: '1:278590582458:web:b1fad34c5282aeb51ddc83',
    messagingSenderId: '278590582458',
    projectId: 'flutterfireanzelly',
    authDomain: 'flutterfireanzelly.firebaseapp.com',
    storageBucket: 'flutterfireanzelly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEbHBUTQFdkbNbxC5r-I1bvsmVcfRQE0U',
    appId: '1:278590582458:android:7ba327ea0832bd2b1ddc83',
    messagingSenderId: '278590582458',
    projectId: 'flutterfireanzelly',
    storageBucket: 'flutterfireanzelly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB900Tcj-KBjwf7JX8fZoW1xS8Vu7M8fZI',
    appId: '1:278590582458:ios:53320e350c7d535c1ddc83',
    messagingSenderId: '278590582458',
    projectId: 'flutterfireanzelly',
    storageBucket: 'flutterfireanzelly.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB900Tcj-KBjwf7JX8fZoW1xS8Vu7M8fZI',
    appId: '1:278590582458:ios:53320e350c7d535c1ddc83',
    messagingSenderId: '278590582458',
    projectId: 'flutterfireanzelly',
    storageBucket: 'flutterfireanzelly.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCjfmNqQ6znpD_sOg9nKWkJp6KFekli-0',
    appId: '1:278590582458:web:f1eed2e57469ab6a1ddc83',
    messagingSenderId: '278590582458',
    projectId: 'flutterfireanzelly',
    authDomain: 'flutterfireanzelly.firebaseapp.com',
    storageBucket: 'flutterfireanzelly.appspot.com',
  );

}