// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwaOZUjpmzKenZc6HP2veXA1vG9Z6nZYA',
    appId: '1:945521403880:web:1c09786d9f0f85102a665d',
    messagingSenderId: '945521403880',
    projectId: 'notes-9d6bd',
    authDomain: 'notes-9d6bd.firebaseapp.com',
    storageBucket: 'notes-9d6bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzYx2hDeyheXcvst9sGovsNkuOTlz3ig',
    appId: '1:945521403880:android:f5352f7a0c1e57aa2a665d',
    messagingSenderId: '945521403880',
    projectId: 'notes-9d6bd',
    storageBucket: 'notes-9d6bd.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfwAC1PjupWrFdLt5__AdAs4dGunxeIGo',
    appId: '1:945521403880:ios:cfca8ee60b48b65f2a665d',
    messagingSenderId: '945521403880',
    projectId: 'notes-9d6bd',
    storageBucket: 'notes-9d6bd.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfwAC1PjupWrFdLt5__AdAs4dGunxeIGo',
    appId: '1:945521403880:ios:cfca8ee60b48b65f2a665d',
    messagingSenderId: '945521403880',
    projectId: 'notes-9d6bd',
    storageBucket: 'notes-9d6bd.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwaOZUjpmzKenZc6HP2veXA1vG9Z6nZYA',
    appId: '1:945521403880:web:e0c6062145dafe1c2a665d',
    messagingSenderId: '945521403880',
    projectId: 'notes-9d6bd',
    authDomain: 'notes-9d6bd.firebaseapp.com',
    storageBucket: 'notes-9d6bd.appspot.com',
  );

}